variables:
- name: BuildParameters.solution
  value: '**\*.sln'

name: $(Major).$(Minor).$(Patch).$(Build)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: DotNetCoreCLI@2
    displayName: "Build Solution"
    inputs:
      command: 'build'
      versioningScheme: byEnvVar
      versionEnvVar: Build.BuildNumber
      projects: $(BuildParameters.solution)
      configuration: $(BuildConfiguration)
      arguments: /p:Version=$(Build.BuildNumber)
  # - task: DotNetCoreCLI@2
  #   displayName: "Pack Project"
  #   inputs:
  #     command: 'pack'
  #     packagesToPack: $(BuildParameters.solution)
  #     versioningScheme: byEnvVar
  #     versionEnvVar: PackageVersion
  #     configuration: $(BuildConfiguration)
  #     arguments: /p:Version=$(Build.BuildNumber)
# https://github.com/microsoft/azure-pipelines-tasks/issues/11640
  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: custom
      custom: pack
      arguments: >
        RfmOpenThings.sln
        --no-build
        --output $(Build.ArtifactStagingDirectory)
        -p:PackageVersion=$(PackageVersion)
        -p:Configuration=$(BuildConfiguration)
  - task: GitHubRelease@1
    displayName: "Publish Relase To GitHub"
    inputs:
      gitHubConnection: 'GitHub PAT'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'v$(Build.BuildNumber)'
      title: 'v$(Build.BuildNumber) - $(BuildConfiguration) - $(Build.SourceBranchName)'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
